config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'teams#index'
  resources :teams do
    resources :players
  end
  
  resources :games do
    get 'points', on: :member
  end
  resources :tournaments
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :team_1,class_name: 'Team', foreign_key: 'team_1_id'
  belongs_to :team_2,class_name: 'Team', foreign_key: 'team_2_id'
  belongs_to :tournament, optional: true

  before_create :assign_points
  before_update :assign_points

  validates :team_1, presence: true
  validates :team_2, presence: true
  
  private
  def assign_points
    self.team_1_points = 0
    self.team_2_points = 0
    return if team_1_score.blank? && team_2_score.blank?

    if team_1_score > team_2_score
      self.team_1_points = 3
      self.team_2_points = 0
    elsif team_1_score == team_2_score
      self.team_1_points = 1
      self.team_2_points = 1
    else
      self.team_2_points = 3
      self.team_1_points = 0
    end 
  end
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :team

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :age, presence: true
  
end

app/models/team.rb
class Team < ApplicationRecord
    has_many :players,  dependent: :destroy
    has_many :team_1_games, class_name: 'Game', foreign_key: :team_1_id
    has_many :team_2_games, class_name: 'Game', foreign_key: :team_2_id
    has_many :games
    validates :team_name, presence: true
end

app/models/tournament.rb
class Tournament < ApplicationRecord
    has_many :games, dependent: :destroy

    validates :number_of_teams, presence:true, numericality: {greater_than_or_equal_to: 0, allow_nil:false, even:true}
    validates :title, presence:true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  def manager?
    role == 'User::Manager'
  end

  def coordinator?
    role == 'User::Coordinator'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys:[:first_name, :last_name, :role])
    end
    
    include Pundit::Authorization

    rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

    private

    def user_not_authorized
        flash[:alert] = "You are not authorized to perform this action."
        redirect_back(fallback_location: root_path)
    end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
    before_action :set_game, only: %i[show edit update destroy]

    def index
        @games = Game.all
        points_service = PointsService.new
        @points = points_service.call
    end

    def show
        # @game = Game.find(params[:id])
    end

    def new
        @game = Game.new()
    end

    def create
        @game = Game.new(game_params)
        authorize @game
        if @game.save
            redirect_to games_path
       else 
            render :new, status: :unprocessable_entity
       end
    end

    def edit
    
    end

    def update
        
        authorize @game
        if @game.update(game_params)
            redirect_to games_path
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        authorize @game
        @game.destroy
        redirect_to games_path(@game)
    end

    private
    def set_game
        @game = Game.find(params[:id])
    end

    def game_params
        params.require(:game).permit(:team_1_id , :team_2_id, :team_1_score, :team_2_score, :tournament_id)
    end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
    before_action :set_player, only: %i[show edit update destroy]
    before_action :set_team

    def new  
        @player = @team.players.new()
    end

    def create
        @player = @team.players.new(player_params)
        authorize @player
        if @player.save
            redirect_to @team
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit
    end

    def update
        authorize @player
        if @player.update(player_params)
            redirect_to @team
        else
            render :edit , status: :unprocessable_entity
        end
    end
  
    def destroy 
        authorize @player
        @player.destroy
        redirect_to @team
    end

    private
    def set_team 
        @team = Team.find(params[:team_id])
    end

    def set_player 
        @player = Player.find(params[:id])
    end

    def player_params
        params.require(:player).permit(:first_name, :last_name, :age)
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, :except => [:index]


  def index
    @teams = Team.all
  end

  def show
  end

  def new
    @team = Team.new
  end

  def edit
  end

  def create
    @team = Team.new(team_params)
    authorize @team
    if @team.save
      redirect_to team_url(@team), notice: "Team was successfully created." 
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    authorize @team
    if @team.update(team_params)
      redirect_to team_url(@team), notice: "Team was successfully updated." 
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    Game.where(team_1_id:@team.id).or(Game.where(team_2_id:@team.id)).destroy_all
    authorize @team
    @team.destroy
    redirect_to teams_url, notice: "Team was successfully destroyed." 
  end

  private
    def set_team
      @team = Team.find(params[:id])
    end

    def team_params
      params.require(:team).permit(:team_name)
    end
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
    before_action :set_tournament, only: %i[show edit update destroy]
    
    def index
        @tournaments = Tournament.all
    end
    
    def show 
        @games = @tournament.games
    end
    
    def new
        @tournament = Tournament.new()
    end
  
    def create
        @tournament = Tournament.new(tournament_params)
      
        if @tournament.save
            redirect_to @tournament
        else
            render :new, status: :unprocessable_entity
        end
  
        total_points = PointsService.new
        @points = total_points.call
        @points = @points[0..@tournament.number_of_teams-1]
        while @points.length > 0
            @tournament.games.create(team_1_id: @points[0][0], team_2_id: @points.last[0])
            @points.shift
            @points.pop
        end
    end
    
    def update
        if @tournament.update(tournament_params)
            redirect_to @tournament
        else
            render :edit, status: :unprocessable_entity
        end
    end
    
    def destroy
        @tournament.destroy
        redirect_to tournaments_path
    end
    
    private
    def set_tournament  
        @tournament = Tournament.find(params[:id])
    end
    
    def tournament_params
        params.require(:tournament).permit(:title, :number_of_teams)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/views/games/_form.html.slim
= form_with model: game do |form|
    p
        = form.label :team_1_id
        br
        = form.select :team_1_id , Team.pluck(:team_name, :id)

    p
        = form.label :team_2_id
        br
        = form.select :team_2_id , Team.pluck(:team_name, :id)

    p
        = form.label :team_1_score
        br
        = form.number_field :team_1_score

    p
        = form.label :team_2_score
        br
        = form.number_field :team_2_score
    
    p
        = form.submit

app/views/games/edit.html.slim
h1 Edit Game
= render 'form', {game:@game, team:@team}

app/views/games/index.html.slim
h1 Games 

table class="table table-striped table-hover"
    thead 
        tr 
            th Team 1
            th Team 2
            th Team 1 Score
            th Team 2 Score
            - if current_user && current_user.manager?
              th
              th
    tbody 
        - @games.each do |game|
            tr
                td = game.team_1.team_name
                td = game.team_2.team_name
                td = game.team_1_score
                td = game.team_2_score
                - if current_user && current_user.manager?
                  td = link_to 'Edit game', edit_game_path(game)
                  td = link_to  'Delete game', game_path(game), method: :delete

- if current_user && current_user.manager?
  = link_to 'Add a new game', new_game_path(@team)

h1 Team Points
table class="table table-striped table-hover" style="width: 50rem;"
  thead
    tr 
      th Team
      th Points
  tbody
    - @points.each do |team|
      tr
        td 
          = Team.find(team[0]).team_name
          
        td
          = team[1]

app/views/games/new.html.slim
h1 New Game
= render 'form', {game:@game,team:@team }

= link_to 'Back', games_path

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Team League</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
     <%= render 'teams/header'%>
     <div class="container">
     <br/>
     <%= yield %>
     <p class="notice"><%= notice %></p>
     <p class="alert"><%= alert %></p>
     
     </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/players/_form.html.slim
= form_with model:[team, player] do |form|
    div
        p
            = form.label :first_name
            br
            = form.text_field :first_name
        p
            = form.label :last_name
            br
            = form.text_field :last_name
        p 
           = form.label :age
           br
           = form.number_field :age

        ul
            - player.errors.full_messages_for(:player_name).each do |error|
                li
                    = error
    div
        = form.submit 'Submit'

app/views/players/_player.html.slim
p
    strong Player First Name:
    = player.first_name
p
    strong Player Last Name:
    = player.last_name 
p
    strong Player Age:
    = player.age

= link_to 'Edit player information', edit_team_player_path(params[:id],player.id)
br
= link_to 'Delete player', team_player_path(@team.id, player.id), method: :delete
br

app/views/players/edit.html.slim
h1 Edit player information
= render 'form', {team:@team, player:@player}

app/views/players/new.html.slim
h1 Add a new player
= render 'form', {team:@team, player:@player}

app/views/tournaments/_form.html.slim
= form_with model: tournament do |form|
    div
        = form.label :title
        = form.text_field :title
    div 
        = form.label :number_of_teams
        = form.number_field :number_of_teams
    div
        = form.submit 'Submit'

app/views/tournaments/edit.html.slim
h1 Edit Tournament 

= render 'form', tournament: @tournament

app/views/tournaments/index.html.slim
h1 Tournaments
ul 
  - @tournaments.each do |tournament|
    li
      = link_to tournament.title, tournament_path(tournament)

- if current_user && current_user.manager?
  = link_to 'New Tournament', new_tournament_path

app/views/tournaments/new.html.slim
h1 New Tournament
= render 'form', tournament: @tournament
br
= link_to 'back', tournaments_path

app/views/tournaments/show.html.slim
h1 #{@tournament.title} Games
table class="table table-striped table-hover"
  thead
    tr
      th Team1
      th Team2
      th Team1 score
      th Team2 score
  tbody
  - @games.each do |game|
    tr
      td = Team.find(game.team_1_id).team_name
      td = Team.find(game.team_2_id).team_name
      td = game.team_1_score
      td = game.team_2_score
  br

- if current_user && current_user.manager?
  br
  = link_to 'Edit', edit_tournament_path(@tournament)
  br
  = link_to 'Delete', tournament_path(@tournament), method: :delete